# Generated by Django 5.2.17 on 2026-10-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_householdmember'),
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('meal_date', models.DateField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_slots', to='households.household')),
                ('meal_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='meals.mealitem')),
            ],
            options={
                'ordering': ['meal_date', 'meal_type'],
                'unique_together': {('household', 'meal_type', 'meal_date')},
            },
        ),
    ]
