# Generated by Django 5.2.17 on 2026-10-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_mealslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mealitem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='meal_items', to='meals.ingredient'),
        ),
    ]
