# Generated by Django 5.2.17 on 2026-10-05 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_ingredient_mealitem_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
    ]
